/* =========================================================
   Views B: Aktivitas, Penerima & Stakeholder, Evidence,
            Pengetahuan & Pembelajaran, Dokumen & Operasional
   ========================================================= */

/* ================= AKTIVITAS ================= */
VIEWS.aktivitas = () => {
  const f = S.f; const data = rows('Activities').filter(a => (!f.aLs || a.landscapeId === f.aLs) && (!f.aSrc || a.sumber === f.aSrc) && (!f.aSt || a.status === f.aSt));
  const kobo = data.filter(a => a.sumber === 'KoboToolbox').length;
  const html = pageHead(t('aktivitas'), 'Log kegiatan lapangan dengan lokasi, peserta, dan kode anggaran. Data dari KoboToolbox masuk sebagai "Perlu Verifikasi".', `<button class="btn edit-only" data-act="kobo">${ic('refresh')} Sinkron KoboToolbox</button><button class="btn primary edit-only" data-act="add" data-id="Activities" data-def='${esc(JSON.stringify({ tanggal: CONFIG.TODAY, sumber: 'Manual', status: 'Perlu Verifikasi' }))}'>${ic('plus')} Catat kegiatan</button><button class="btn" data-act="exportcsv" data-id="Activities">${ic('down')} ${t('export')}</button>`) + `
  <div class="grid g4 mb"><div class="panel kpi"><b>${nf(data.length)}</b><span>Kegiatan tercatat</span></div><div class="panel kpi"><b>${nf(sum(data, a => a.pesertaP))} / ${nf(sum(data, a => a.pesertaL))}</b><span>Peserta perempuan / laki-laki</span></div><div class="panel kpi"><b>${pctf(data.length ? kobo / data.length * 100 : null)}</b><span>Masuk lewat KoboToolbox</span></div><div class="panel kpi"><b>${nf(data.filter(a => a.status === 'Perlu Verifikasi').length)}</b><span>Perlu verifikasi</span></div></div>
  <div class="filters"><label>Landscape<select data-fk="aLs"><option value="">Semua</option>${rows('Landscapes').map(l => `<option value="${l.id}" ${f.aLs === l.id ? 'selected' : ''}>${esc(l.nama)}</option>`).join('')}</select></label>
  <label>Sumber<select data-fk="aSrc"><option value="">Semua</option>${['Manual', 'KoboToolbox'].map(v => `<option ${f.aSrc === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label>
  <label>Status<select data-fk="aSt"><option value="">Semua</option>${['Perlu Verifikasi', 'Terverifikasi'].map(v => `<option ${f.aSt === v ? 'selected' : ''}>${v}</option>`).join('')}</select></label></div>
  ${table('acts', { data, pageSize: 15, onRow: r => openForm('Activities', r), cols: [{ k: 'tanggal', label: 'Tanggal', render: r => fdate(r.tanggal) }, { k: 'nama', label: 'Kegiatan', render: r => `${esc(r.nama)}<br><span class="muted small">${esc(nameOf('Outputs', r.outputId, 'kode'))} · ${esc(nameOf('Sites', r.siteId))}</span>` }, { k: 'landscapeId', label: 'Landscape', text: r => nameOf('Landscapes', r.landscapeId), render: r => esc(nameOf('Landscapes', r.landscapeId)) }, { k: 'pp', label: 'P / L', num: 1, render: r => `${r.pesertaP} / ${r.pesertaL}`, sortv: r => +r.pesertaP + +r.pesertaL }, { k: 'hadir', label: 'Daftar hadir', num: 1, render: r => (r.peserta || []).length, sortv: r => (r.peserta || []).length }, { k: 'realisasi', label: 'Realisasi', num: 1, render: r => r.realisasi ? `<span class="small">${rp(r.realisasi)}</span><br><span class="muted small">${esc(r.kodeAnggaran)}</span>` : '–' }, { k: 'sumber', label: 'Sumber', render: r => `<span class="badge ${r.sumber === 'KoboToolbox' ? 'blue' : ''}">${esc(r.sumber)}</span>` }, { k: 'status', label: 'Status', render: r => `<span class="badge ${r.status === 'Terverifikasi' ? 'green' : 'yellow'}">${esc(r.status)}</span>` }],
    actions: r => `<span class="edit-only flex" style="gap:4px;flex-wrap:nowrap">${r.status !== 'Terverifikasi' ? act('verAct', r.id, 'Verifikasi', '', 'primary') : ''}${crudActs('Activities', r)}</span>` })}`;
  return { html, after: bindFk };
};
function bindFk() { $$('[data-fk]').forEach(s => s.onchange = e => { S.f[s.dataset.fk] = e.target.value; Object.keys(TS).forEach(k => TS[k].page = 0); render(); }); }
ACT.verAct = async el => { const r = byId('Activities', el.dataset.id); await saveRec('Activities', { ...r, status: 'Terverifikasi' }, 'Diverifikasi'); toast('Kegiatan terverifikasi.'); render(); };
ACT.kobo = async el => { el.disabled = true; try { const out = await API.syncKobo(CONFIG.USER); out.forEach(r => upsertLocal('Activities', r)); toast(out.length ? `${out.length} submission baru dari KoboToolbox. Periksa lalu verifikasi.` : 'Tidak ada submission baru.'); render(); } catch (e) { toast('Sinkron gagal: ' + e.message, 1); el.disabled = false; } };

/* ================= PENERIMA & STAKEHOLDER ================= */
VIEWS.penerima = () => {
  const tab = curTab('penerima', 'ben'); let body = '';
  const maskToggle = `<label class="check" style="margin-left:auto"><input type="checkbox" id="maskT" ${S.mask ? 'checked' : ''} ${S.pub ? 'disabled' : ''}> Samarkan data pribadi</label>`;
  if (tab === 'ben') {
    const f = S.f; const data = rows('Beneficiaries').filter(b => (!f.bLs || b.landscapeId === f.bLs) && (!f.bKel || b.kelompok === f.bKel) && (!f.bJk || b.jk === f.bJk));
    body = `<div class="grid g4 mb"><div class="panel kpi"><b>${nf(data.length)}</b><span>Penerima terdaftar</span></div><div class="panel kpi"><b>${pctf(data.length ? data.filter(b => b.jk === 'P').length / data.length * 100 : null)}</b><span>Perempuan</span></div><div class="panel kpi"><b>${nf(data.filter(b => b.rentan).length)}</b><span>Kelompok rentan</span></div><div class="panel kpi"><b>${nf(data.filter(b => !b.consent).length)}</b><span>Belum ada consent</span></div></div>
    <div class="filters"><label>Landscape<select data-fk="bLs"><option value="">Semua</option>${rows('Landscapes').map(l => `<option value="${l.id}" ${f.bLs === l.id ? 'selected' : ''}>${esc(l.nama)}</option>`).join('')}</select></label>
    <label>Kelompok<select data-fk="bKel"><option value="">Semua</option>${uniq(rows('Beneficiaries').map(b => b.kelompok)).map(k => `<option ${f.bKel === k ? 'selected' : ''}>${esc(k)}</option>`).join('')}</select></label>
    <label>Jenis kelamin<select data-fk="bJk"><option value="">Semua</option><option value="P" ${f.bJk === 'P' ? 'selected' : ''}>Perempuan</option><option value="L" ${f.bJk === 'L' ? 'selected' : ''}>Laki-laki</option></select></label>${maskToggle}</div>
    ${table('ben', { data, pageSize: 15, cols: [{ k: 'id', label: 'ID' }, { k: 'nama', label: 'Nama' }, { k: 'nik', label: 'NIK', render: r => `<span class="${S.mask ? 'masked' : ''}">${esc(maskStr(r.nik))}</span>` }, { k: 'jk', label: 'JK' }, { k: 'umur', label: 'Umur', num: 1, render: r => age(r.tglLahir), sortv: r => age(r.tglLahir) }, { k: 'desa', label: 'Desa' }, { k: 'landscapeId', label: 'Landscape', text: r => nameOf('Landscapes', r.landscapeId), render: r => esc(nameOf('Landscapes', r.landscapeId)) }, { k: 'kelompok', label: 'Kelompok' }, { k: 'flags', label: 'Status', render: r => `${r.rentan ? '<span class="badge sand">Rentan</span> ' : ''}${r.consent ? '<span class="badge green">Consent</span>' : '<span class="badge red">Tanpa consent</span>'}` }, { k: 'hp', label: 'No. HP', render: r => `<span class="${S.mask ? 'masked' : ''}">${esc(maskStr(r.hp, 3))}</span>` }], actions: r => crudActs('Beneficiaries', r) })}`;
  } else if (tab === 'dup') {
    const g = dupGroups();
    body = `<div class="alert info">Kemungkinan duplikat dicari dari kombinasi nama, desa, dan tanggal lahir (tanpa membedakan huruf besar dan spasi). Gabungkan data yang sama, atau tandai bukan duplikat.</div>` + (g.length ? g.map((grp, gi) => `<div class="panel mb"><div class="panel-h"><h2>Grup ${gi + 1}: ${esc(grp[0].nama)}</h2><div class="right edit-only"><button class="btn sm" data-act="notDup" data-id="${grp.map(b => b.id).join(',')}">Bukan duplikat</button><button class="btn sm primary" data-act="merge" data-id="${grp.map(b => b.id).join(',')}">Gabungkan ke ${esc(grp[0].id)}</button></div></div><div class="table-wrap"><table class="t"><thead><tr><th>ID</th><th>Nama</th><th>Desa</th><th>Tgl lahir</th><th>HP</th><th>Terdaftar</th><th>Dipakai di kegiatan</th></tr></thead><tbody>${grp.map(b => `<tr><td>${esc(b.id)}</td><td>${esc(b.nama)}</td><td>${esc(b.desa)}</td><td>${esc(maskStr(b.tglLahir, 4))}</td><td>${esc(maskStr(b.hp, 3))}</td><td>${fdate(b.terdaftar)}</td><td>${rows('Activities').filter(a => (a.peserta || []).includes(b.id)).length}</td></tr>`).join('')}</tbody></table></div></div>`).join('') : '<div class="panel empty">Tidak ada kemungkinan duplikat. Registry bersih.</div>');
  } else {
    const d = rows('Stakeholders'); const lv = ['Tinggi', 'Sedang', 'Rendah'];
    body = `<div class="grid g-7-5"><div>${table('stk', { data: d, cols: [{ k: 'nama', label: 'Lembaga' }, { k: 'tipe', label: 'Tipe' }, { k: 'landscapeId', label: 'Landscape', render: r => esc(nameOf('Landscapes', r.landscapeId)) }, { k: 'peran', label: 'Peran' }, { k: 'pengaruh', label: 'Pengaruh' }, { k: 'kepentingan', label: 'Kepentingan' }], actions: r => crudActs('Stakeholders', r) })}</div>
    <div class="panel"><div class="panel-h"><h2>Matriks pengaruh × kepentingan</h2><p>Kuadran kanan atas perlu dilibatkan paling erat.</p></div><div class="matrix"><div></div>${lv.slice().reverse().map(k => `<div class="ax">Kepentingan ${k.toLowerCase()}</div>`).join('')}${lv.map(p => `<div class="ax">Pengaruh ${p.toLowerCase()}</div>${lv.slice().reverse().map(k => `<div class="cell ${p === 'Tinggi' && k === 'Tinggi' ? 'hot' : ''}">${d.filter(s => s.pengaruh === p && s.kepentingan === k).map(s => `<span class="chip" title="${esc(s.nama)}">${esc(s.nama.length > 18 ? s.nama.slice(0, 17) + '…' : s.nama)}</span>`).join('')}</div>`).join('')}`).join('')}</div></div></div>`;
  }
  const addBtn = tab === 'stk' ? `<button class="btn primary edit-only" data-act="add" data-id="Stakeholders">${ic('plus')} Tambah stakeholder</button><button class="btn" data-act="exportcsv" data-id="Stakeholders">${ic('down')} ${t('export')}</button>` : `<button class="btn primary edit-only" data-act="addBen">${ic('plus')} Daftarkan penerima</button><button class="btn" data-act="exportcsv" data-id="Beneficiaries">${ic('down')} ${t('export')}</button>`;
  return { html: pageHead(t('penerima'), 'Registry dengan ID unik, cek duplikat, persetujuan data, dan penyamaran data pribadi sesuai UU PDP.', addBtn) + tabs('penerima', [['ben', 'Penerima manfaat'], ['dup', `Cek duplikat (${dupGroups().length})`], ['stk', 'Stakeholder']]) + body,
    after: () => { bindFk(); const m = $('#maskT'); if (m) m.onchange = e => { S.mask = e.target.checked; toast(S.mask ? 'Data pribadi disamarkan.' : 'Data pribadi ditampilkan. Akses ini tercatat.'); if (!S.mask) logLocal('Lihat data pribadi', 'Beneficiaries', '-', 'Masking dimatikan'); render(); }; } };
};
ACT.addBen = () => openForm('Beneficiaries', null, { defaults: { terdaftar: CONFIG.TODAY, consent: true },
  beforeSave: async o => { const d = rows('Beneficiaries').find(b => b.id !== o.id && dupKey(b) === dupKey(o)); if (d) return (await confirmBox('Kemungkinan duplikat', `Sudah ada <b>${esc(d.nama)}</b> (${d.id}) dengan desa dan tanggal lahir yang sama. Tetap simpan sebagai orang berbeda?`, 'Tetap simpan')) ? undefined : false; if (!o.consent) toast('Catatan: penerima ini belum memberi persetujuan data.', 1); } });
ACT.merge = async el => {
  const ids = el.dataset.id.split(','); const keep = ids[0];
  if (!(await confirmBox('Gabungkan data', `Data ${ids.slice(1).join(', ')} akan digabung ke <b>${keep}</b>. Daftar hadir kegiatan dipindahkan, lalu data ganda masuk tempat sampah.`, 'Gabungkan'))) return;
  const base = { ...byId('Beneficiaries', keep) }; ids.slice(1).forEach(id => { const o = byId('Beneficiaries', id); ['nik', 'hp'].forEach(k => { if (!base[k] && o[k]) base[k] = o[k]; }); });
  await saveRec('Beneficiaries', base, 'Gabung dari ' + ids.slice(1).join(','));
  for (const a of rows('Activities').filter(a => (a.peserta || []).some(p => ids.slice(1).includes(p)))) await saveRec('Activities', { ...a, peserta: uniq(a.peserta.map(p => ids.includes(p) ? keep : p)) }, 'Peserta digabung');
  for (const id of ids.slice(1)) { const r = await API.remove('Beneficiaries', id, CONFIG.USER); r && upsertLocal('Beneficiaries', r); }
  toast('Data digabungkan.'); render();
};
ACT.notDup = async el => { const cur = (S.db.Settings || []).find(s => s.id === 'bukanDuplikat'); const v = uniq(String(cur ? cur.nilai : '').split(',').concat(el.dataset.id.split(','))).filter(Boolean).join(','); await saveRec('Settings', { id: 'bukanDuplikat', nilai: v }, 'Tandai bukan duplikat'); toast('Ditandai bukan duplikat.'); render(); };

/* ================= EVIDENCE ================= */
const EV_ICON = { 'Foto': 'image', 'Video': 'video', 'Peta': 'map', 'Data Survei': 'table', 'Daftar Hadir': 'users', 'Laporan Kegiatan': 'file' };
const EV_BG = { 'Foto': '#127A86', 'Video': '#0A2E3F', 'Peta': '#4F7A45', 'Data Survei': '#0E4A5C', 'Daftar Hadir': '#8C6A2A', 'Laporan Kegiatan': '#3F6570' };
const evImg = e => e.thumb || (e.url && /^data:image|\.(png|jpe?g|webp)$/i.test(e.url) ? e.url : '');
const evidenceCard = e => `<button class="card" data-act="evd" data-id="${e.id}"><div class="thumb" style="background:${evImg(e) ? `url('${esc(evImg(e))}') center/cover` : (EV_BG[e.jenis] || '#127A86')}">${evImg(e) ? '' : ic(EV_ICON[e.jenis] || 'file')}</div><div class="body"><span class="badge">${esc(e.jenis)}</span><h3>${esc(e.judul)}</h3><div class="meta">${fdate(e.tanggal)} · ${esc(nameOf('Landscapes', e.landscapeId))}</div><div class="meta">${esc(e.tags || '')}</div></div></button>`;
VIEWS.evidence = () => {
  const f = S.f; const q = norm(f.eQ || '');
  const data = rows('Evidence').filter(e => (!f.eLs || e.landscapeId === f.eLs) && (!f.eJ || e.jenis === f.eJ) && (!f.eInd || e.indicatorId === f.eInd) && (!q || norm(e.judul + ' ' + e.tags).includes(q))).sort((a, b) => b.tanggal.localeCompare(a.tanggal));
  const shown = data.slice(0, f.eN || 24);
  const html = pageHead(t('evidence'), 'Bukti pendukung capaian dan kegiatan. File disimpan di Google Drive, otomatis dalam folder per landscape.', `<button class="btn primary edit-only" data-act="upEv">${ic('upload')} Unggah evidence</button><button class="btn" data-act="exportcsv" data-id="Evidence">${ic('down')} ${t('export')}</button>`) + `
  <div class="filters"><label>Cari<input type="search" id="eQ" value="${esc(f.eQ || '')}" placeholder="Judul atau tag"></label>
  <label>Jenis<select data-fk="eJ"><option value="">Semua</option>${uniq(rows('Evidence').map(e => e.jenis)).map(j => `<option ${f.eJ === j ? 'selected' : ''}>${esc(j)}</option>`).join('')}</select></label>
  <label>Landscape<select data-fk="eLs"><option value="">Semua</option>${rows('Landscapes').map(l => `<option value="${l.id}" ${f.eLs === l.id ? 'selected' : ''}>${esc(l.nama)}</option>`).join('')}</select></label>
  <label>Indikator<select data-fk="eInd"><option value="">Semua</option>${rows('Indicators').map(i => `<option value="${i.id}" ${f.eInd === i.id ? 'selected' : ''}>${esc(i.kode + ' ' + i.nama)}</option>`).join('')}</select></label>
  <span class="muted small" style="margin-top:16px">${nf(data.length)} file</span></div>
  ${shown.length ? `<div class="cards">${shown.map(evidenceCard).join('')}</div>${data.length > shown.length ? `<div class="flex mt" style="justify-content:center"><button class="btn" data-act="moreEv">Tampilkan lebih banyak</button></div>` : ''}` : '<div class="panel empty">Tidak ada evidence yang cocok dengan filter. Ubah filter atau unggah evidence baru.</div>'}`;
  return { html, after: () => { bindFk(); const i = $('#eQ'); i.oninput = debounce(() => { S.f.eQ = i.value; render(); setTimeout(() => { const j = $('#eQ'); j.focus(); j.setSelectionRange(j.value.length, j.value.length); }); }, 300); } };
};
ACT.moreEv = () => { S.f.eN = (S.f.eN || 24) + 24; render(); };
ACT.evd = el => evidenceDetail(el.dataset.id);
function evidenceDetail(id) {
  const e = byId('Evidence', id); if (!e) return; const img = evImg(e);
  const used = rows('IndicatorActuals').filter(a => (a.evidenceIds || []).includes(id));
  modal({ wide: true, title: esc(e.judul), body: `<div class="grid g2"><div>${img ? `<img src="${esc(img)}" alt="${esc(e.judul)}" style="width:100%;border-radius:8px">` : `<div class="card" style="cursor:default"><div class="thumb" style="height:200px;background:${EV_BG[e.jenis] || '#127A86'}">${ic(EV_ICON[e.jenis] || 'file')}</div></div>`}
    ${e.url ? `<a class="btn mt" href="${esc(e.url)}" target="_blank" rel="noopener">${ic('eye')} Buka file</a>` : '<p class="muted small">File contoh: pada data dummy tidak ada file asli.</p>'}</div>
    <div><dl class="dl"><dt>Jenis</dt><dd>${esc(e.jenis)}</dd><dt>Tanggal</dt><dd>${fdate(e.tanggal)}</dd><dt>Landscape</dt><dd>${esc(nameOf('Landscapes', e.landscapeId))}</dd><dt>Indikator</dt><dd>${e.indicatorId ? `<a href="#" data-act="ind" data-id="${e.indicatorId}">${esc(nameOf('Indicators', e.indicatorId))}</a>` : '–'}</dd><dt>Aktivitas</dt><dd>${esc(nameOf('Activities', e.activityId))}</dd><dt>Tag</dt><dd>${esc(e.tags || '–')}</dd><dt>Ukuran</dt><dd>${esc(e.ukuran || '–')}</dd><dt>Pengunggah</dt><dd>${esc(e.pengunggah || '–')}</dd><dt>Koordinat</dt><dd>${e.lat ? e.lat + ', ' + e.lng : '–'}</dd><dt>Dipakai di capaian</dt><dd>${used.length ? used.map(a => `${a.periode} · ${esc(nameOf('Landscapes', a.landscapeId))} ${statusBadge(a.status)}`).join('<br>') : 'Belum ditautkan'}</dd></dl></div></div>`,
    foot: `<span class="edit-only flex">${act('edit', 'Evidence|' + id, 'Ubah metadata', 'edit')}${act('del', 'Evidence|' + id, 'Hapus', 'trash', 'danger')}</span><button class="btn" data-close>Tutup</button>` });
}
ACT.upEv = () => {
  const fields = SCHEMA.Evidence.fields.filter(f => f.k !== 'url');
  const m = modal({ wide: true, title: 'Unggah evidence', body: `<div class="form"><div class="f full"><label for="evFile">File <span class="req">*</span></label><input type="file" id="evFile" accept="image/*,video/*,.pdf,.doc,.docx,.xls,.xlsx,.csv"><span class="hint">Maksimal 10 MB. Foto dari HP menyimpan tanggal dan lokasi di metadata.</span><span class="err" id="evErr"></span></div>${fields.map(f => fieldHTML(f, { tanggal: CONFIG.TODAY, pengunggah: CONFIG.USER }[f.k] || '')).join('')}</div>`,
    foot: `<button class="btn" data-close>${t('cancel')}</button><button class="btn primary" id="evGo">${ic('upload')} Unggah</button>` });
  const el = m.el; $('#evFile', el).onchange = e => { const fl = e.target.files[0]; if (fl && !$('[name=judul]', el).value) $('[name=judul]', el).value = fl.name.replace(/\.[^.]+$/, ''); };
  $$('[data-gps]', el).forEach(b => b.onclick = () => navigator.geolocation && navigator.geolocation.getCurrentPosition(p => { $('[name=lat]', el).value = p.coords.latitude.toFixed(5); $('[name=lng]', el).value = p.coords.longitude.toFixed(5); }));
  $('#evGo', el).onclick = async () => {
    const fl = $('#evFile', el).files[0]; $('#evErr', el).textContent = fl ? '' : 'Pilih file dulu.'; const o = readForm(el, fields); if (!validate(el, fields, o) || !fl) return;
    if (fl.size > 10 * 1024 * 1024) { $('#evErr', el).textContent = 'File lebih dari 10 MB. Kompres dulu atau unggah langsung ke Drive lalu tempel tautannya.'; return; }
    $('#evGo', el).disabled = true; $('#evGo', el).textContent = 'Mengunggah…';
    const dataUrl = await new Promise(r => { const fr = new FileReader(); fr.onload = () => r(fr.result); fr.readAsDataURL(fl); });
    try { const r = await API.uploadEvidence(o, { name: fl.name, type: fl.type, size: fl.size, dataUrl }, CONFIG.USER); upsertLocal('Evidence', r); m.close(); toast('Evidence terunggah.'); render(); }
    catch (e) { toast('Unggah gagal: ' + e.message, 1); $('#evGo', el).disabled = false; $('#evGo', el).textContent = 'Unggah'; }
  };
};

/* ================= PENGETAHUAN & PEMBELAJARAN ================= */
VIEWS.pengetahuan = () => {
  const tab = S.pub ? 'kp' : curTab('pengetahuan', 'kp'); let body = ''; let add = '';
  if (tab === 'kp') {
    const d = rows('Knowledge').filter(k => !S.pub || k.publik);
    add = `<button class="btn primary edit-only" data-act="add" data-id="Knowledge">${ic('plus')} Tambah produk</button>`;
    body = `<div class="cards">${d.map(k => `<div class="card" style="cursor:default"><div class="thumb" style="height:70px;background:${({ Panduan: '#127A86', 'Policy Brief': '#0A2E3F', Laporan: '#0E4A5C', Infografis: '#4F7A45' })[k.tipe] || '#3F6570'}">${ic('book')}</div><div class="body"><div class="flex"><span class="badge">${esc(k.tipe)}</span><span class="badge">${esc(k.bahasa)}</span>${k.publik ? '<span class="badge green">Publik</span>' : ''}</div><h3>${esc(k.judul)}</h3><p class="small muted" style="margin:0">${esc(k.ringkasan)}</p><div class="meta">${fdate(k.tanggal)} · ${esc(nameOf('Programs', k.programId))}</div><div class="flex edit-only">${act('edit', 'Knowledge|' + k.id, 'Ubah', 'edit')}${iconAct('del', 'Knowledge|' + k.id, 'Hapus', 'trash', 'danger')}</div></div></div>`).join('')}</div>`;
  } else if (tab === 'll') {
    add = `<button class="btn primary edit-only" data-act="add" data-id="Lessons">${ic('plus')} Catat pembelajaran</button>`;
    body = `<div class="grid g2">${rows('Lessons').map(l => { const acts = rows('Actions').filter(a => a.lessonId === l.id); return `<div class="panel"><div class="panel-h"><span class="badge blue">${esc(l.sumber)}</span><span class="muted small">${fdate(l.tanggal)} · ${esc(nameOf('Landscapes', l.landscapeId))}</span></div><h3 style="font-size:16px;margin-bottom:8px">${esc(l.judul)}</h3><dl class="dl"><dt>Konteks</dt><dd>${esc(l.konteks)}</dd><dt>Pembelajaran</dt><dd>${esc(l.pembelajaran)}</dd><dt>Rekomendasi</dt><dd>${esc(l.rekomendasi)}</dd><dt>Tindak lanjut</dt><dd>${acts.length ? acts.map(a => `<span class="badge ${a.status === 'Selesai' ? 'green' : a.deadline < CONFIG.TODAY ? 'red' : 'yellow'}">${esc(a.status)}</span> ${esc(a.tindakan)}`).join('<br>') : '<span class="muted">Belum ada</span>'}</dd></dl><div class="flex mt edit-only"><button class="btn sm" data-act="add" data-id="Actions" data-def='${esc(JSON.stringify({ lessonId: l.id, status: 'Belum Mulai' }))}'>${ic('plus')} Tindak lanjut</button>${act('edit', 'Lessons|' + l.id, 'Ubah', 'edit')}</div></div>`; }).join('')}</div>`;
  } else if (tab === 'act') {
    add = `<button class="btn primary edit-only" data-act="add" data-id="Actions" data-def='${esc(JSON.stringify({ status: 'Belum Mulai' }))}'>${ic('plus')} Tambah tindak lanjut</button>`;
    const cols = ['Belum Mulai', 'Proses', 'Selesai'];
    body = `<div class="alert info">Management response: setiap pembelajaran diturunkan jadi tindakan dengan PIC dan tenggat, sehingga siklus data → pembelajaran → keputusan tertutup.</div><div class="kanban" style="--cols:3">${cols.map((c, ci) => `<div class="kcol"><h3>${c} <span class="badge">${rows('Actions').filter(a => a.status === c).length}</span></h3>${rows('Actions').filter(a => a.status === c).map(a => `<div class="kitem ${a.status !== 'Selesai' && a.deadline < CONFIG.TODAY ? 'overdue' : ''}"><b>${esc(a.tindakan)}</b><div class="meta">${esc(a.pic)} · tenggat ${fdate(a.deadline)}${a.status !== 'Selesai' && a.deadline < CONFIG.TODAY ? ' · <b style="color:var(--urchin)">lewat tenggat</b>' : ''}</div><div class="meta">Dari: ${esc(nameOf('Lessons', a.lessonId, 'judul'))}</div><div class="flex mt edit-only" style="gap:4px">${ci > 0 ? `<button class="btn sm" data-act="mvAct" data-id="${a.id}|${cols[ci - 1]}">‹ ${cols[ci - 1]}</button>` : ''}${ci < 2 ? `<button class="btn sm primary" data-act="mvAct" data-id="${a.id}|${cols[ci + 1]}">${cols[ci + 1]} ›</button>` : ''}${iconAct('edit', 'Actions|' + a.id, 'Ubah', 'edit')}</div></div>`).join('')}</div>`).join('')}</div>`;
  } else {
    add = `<button class="btn primary edit-only" data-act="add" data-id="Stories" data-def='${esc(JSON.stringify({ tanggal: CONFIG.TODAY }))}'>${ic('plus')} Tulis cerita</button>`;
    body = `<div class="grid g3">${rows('Stories').map(s => `<article class="story"><span class="badge sand">${esc(nameOf('Landscapes', s.landscapeId))}</span><h3 style="font-size:16px;margin-top:10px">${esc(s.judul)}</h3><blockquote>“${esc(s.kutipan)}”</blockquote><p class="small">${esc(s.cerita)}</p><p class="small muted">${esc(s.narasumber)} · ${fdate(s.tanggal)}<br>Outcome: ${esc(nameOf('Outcomes', s.outcomeId, 'pernyataan'))}</p><div class="flex edit-only">${act('edit', 'Stories|' + s.id, 'Ubah', 'edit')}</div></article>`).join('')}</div>`;
  }
  return pageHead(t('pengetahuan'), 'Produk pengetahuan, lessons learned dari after-action review, tindak lanjut manajemen, dan cerita perubahan dari lapangan.', add) + (S.pub ? '' : tabs('pengetahuan', [['kp', 'Produk pengetahuan'], ['ll', 'Lessons learned'], ['act', 'Tindak lanjut'], ['sc', 'Cerita perubahan']])) + body;
};
ACT.mvAct = async el => { const [id, st] = el.dataset.id.split('|'); await saveRec('Actions', { ...byId('Actions', id), status: st }, 'Status → ' + st); render(); };

/* ================= DOKUMEN & OPERASIONAL ================= */
VIEWS.dokumen = () => {
  const tab = curTab('dokumen', 'doc'); let body = '';
  if (tab === 'doc') {
    body = `<div class="flex mb edit-only"><button class="btn primary" data-act="add" data-id="Documents" data-def='${esc(JSON.stringify({ status: 'Draft', versi: '1.0' }))}'>${ic('plus')} Tambah dokumen</button><button class="btn" data-act="exportcsv" data-id="Documents">${ic('down')} ${t('export')}</button></div>` +
      table('docs', { data: rows('Documents'), cols: [{ k: 'judul', label: 'Dokumen', render: r => `<b>${esc(r.judul)}</b><br><span class="muted small">${esc(r.nomor)}</span>` }, { k: 'jenis', label: 'Jenis' }, { k: 'versi', label: 'Versi', render: r => 'v' + esc(r.versi) }, { k: 'berlaku', label: 'Berlaku', render: r => fdate(r.berlaku) }, { k: 'pemilik', label: 'Pemilik' }, { k: 'status', label: 'Status', render: r => `<span class="badge ${({ Draft: '', Review: 'yellow', Disetujui: 'green', Kedaluwarsa: 'red' })[r.status]}">${esc(r.status)}</span>` }],
        actions: r => `<span class="edit-only flex" style="gap:4px;flex-wrap:nowrap">${r.status === 'Draft' ? act('docSt', r.id + '|Review', 'Ajukan review', '') : ''}${r.status === 'Review' ? act('docSt', r.id + '|Disetujui', 'Setujui', '', 'primary') : ''}${crudActs('Documents', r)}</span>` });
  } else if (tab === 'fin') {
    const bl = rows('BudgetLines'); const byLs = groupBy(bl, b => b.kode.slice(-1));
    body = `<div class="alert info">Keuangan tetap dikelola di sistem keuangan yang ada. MIS hanya membaca export anggaran dan realisasi per kode anggaran, lalu menautkannya ke kegiatan dan capaian. Perbarui lewat menu Migrasi (impor CSV ke tabel BudgetLines).</div>
    <div class="grid g4 mb"><div class="panel kpi"><b>${rp(sum(bl, b => b.anggaran))}</b><span>Total anggaran kegiatan</span></div><div class="panel kpi"><b>${rp(sum(bl, b => b.realisasi))}</b><span>Realisasi</span></div><div class="panel kpi"><b>${pctf(sum(bl, b => b.realisasi) / (sum(bl, b => b.anggaran) || 1) * 100)}</b><span>Serapan</span></div><div class="panel kpi"><b>${fdate((bl[0] || {}).diperbarui)}</b><span>Export terakhir</span></div></div>
    <div class="grid g-7-5"><div class="panel"><div class="panel-h"><h2>Anggaran vs realisasi per landscape</h2></div><div class="chart-box"><canvas id="cFin"></canvas></div></div>
    <div class="panel"><div class="panel-h"><h2>Integrasi fungsi operasional</h2><p>Hasil pemetaan kebutuhan: modul penuh tidak dibangun ulang di MIS.</p></div><div class="table-wrap"><table class="t"><thead><tr><th>Fungsi</th><th>Sistem saat ini</th><th>Mekanisme</th></tr></thead><tbody><tr><td>Keuangan</td><td>Aplikasi akuntansi</td><td><span class="badge blue">Impor CSV berkala</span></td></tr><tr><td>SDM</td><td>Spreadsheet HR</td><td><span class="badge blue">Referensi ID staf</span></td></tr><tr><td>Procurement</td><td>Formulir + Drive</td><td><span class="badge sand">Tautan dokumen</span></td></tr><tr><td>Dokumen</td><td>Google Drive</td><td><span class="badge green">Terhubung</span></td></tr></tbody></table></div></div></div>
    <div class="mt">${table('bl', { data: bl, cols: [{ k: 'kode', label: 'Kode' }, { k: 'uraian', label: 'Uraian' }, { k: 'anggaran', label: 'Anggaran', num: 1, render: r => rp(r.anggaran) }, { k: 'realisasi', label: 'Realisasi', num: 1, render: r => rp(r.realisasi) }, { k: 'p', label: 'Serapan', render: r => pctBar(r.anggaran ? r.realisasi / r.anggaran * 100 : null), sortv: r => r.realisasi / r.anggaran }, { k: 'k', label: 'Kegiatan', num: 1, render: r => rows('Activities').filter(a => a.kodeAnggaran === r.kode).length }], actions: r => crudActs('BudgetLines', r) })}</div>`;
    return { html: pageHead(t('dokumen'), 'Dokumen organisasi dengan versi dan status persetujuan, serta tautan ke data keuangan.') + tabs('dokumen', [['doc', 'Manajemen dokumen'], ['fin', 'Anggaran & integrasi']]) + body,
      after: () => { const ls = rows('Landscapes'); const g = groupBy(rows('BudgetLines'), b => 'LS-0' + b.kode.slice(-1));
        chart('cFin', { type: 'bar', data: { labels: ls.map(l => l.nama), datasets: [{ label: 'Anggaran', data: ls.map(l => sum(g[l.id] || [], b => b.anggaran) / 1e6), backgroundColor: PAL.sand, borderRadius: 4 }, { label: 'Realisasi', data: ls.map(l => sum(g[l.id] || [], b => b.realisasi) / 1e6), backgroundColor: PAL.lagoon, borderRadius: 4 }] }, options: { scales: { y: { ticks: { callback: v => v + ' jt' } } } } }); } };
  }
  return pageHead(t('dokumen'), 'Dokumen organisasi dengan versi dan status persetujuan, serta tautan ke data keuangan.') + tabs('dokumen', [['doc', 'Manajemen dokumen'], ['fin', 'Anggaran & integrasi']]) + body;
};
ACT.docSt = async el => { const [id, st] = el.dataset.id.split('|'); await saveRec('Documents', { ...byId('Documents', id), status: st }, 'Status → ' + st); toast(st === 'Disetujui' ? 'Dokumen disetujui.' : 'Dokumen diajukan untuk review.'); render(); };
