/* =========================================================
   Views C: Pelaporan, Migrasi & Kualitas Data, Admin, Bantuan
   ========================================================= */

/* ================= PELAPORAN ================= */
function donors() { return uniq(rows('Indicators').flatMap(i => String(i.crosswalk || '').split('|').map(s => s.split(':')[0].trim()).filter(s => s && !/^SDG/i.test(s)))).sort(); }
function buildReport(o) {
  const per = o.per, ls = o.ls || null; const lsName = ls ? nameOf('Landscapes', ls) : 'Semua landscape';
  let inds = rows('Indicators'); if (o.tpl === 'donor') inds = inds.filter(i => String(i.crosswalk).includes(o.donor + ':'));
  const code = i => { const m = String(i.crosswalk).split('|').map(s => s.trim()).find(s => s.startsWith(o.donor + ':')); return m ? m.split(':')[1].trim() : ''; };
  const indRows = inds.map(i => { const a = achv(i, ls, per); return [o.tpl === 'donor' ? code(i) : i.kode, i.nama, nf(a.target, 1) + ' ' + i.satuan, nf(a.actual, 1), pctf(a.pct), lightLabel(a.pct)]; });
  const ben = rows('Beneficiaries').filter(b => !ls || b.landscapeId === ls);
  const acts = rows('Activities').filter(a => (!ls || a.landscapeId === ls) && a.tanggal <= (periodObj(per) || {}).selesai && a.tanggal >= (periodObj(per) || {}).mulai);
  const red = inds.filter(i => light(achv(i, ls, per).pct) === 'red');
  const title = { donor: `Laporan Kemajuan untuk ${o.donor}`, ls: `Laporan Capaian ${lsName}`, exec: 'Ringkasan Eksekutif untuk Manajemen' }[o.tpl];
  const sec = [];
  sec.push({ h: 'Ringkasan', p: [`Laporan ini mencakup ${inds.length} indikator untuk ${lsName} sampai periode ${per}. Sebanyak ${inds.filter(i => (achv(i, ls, per).pct || 0) >= 90).length} indikator on track, ${red.length} off track. Hanya capaian berstatus Approved yang dihitung.`, `Selama periode ${per} tercatat ${acts.length} kegiatan dengan ${nf(sum(acts, a => a.pesertaP))} peserta perempuan dan ${nf(sum(acts, a => a.pesertaL))} peserta laki-laki. Registry penerima manfaat berisi ${nf(ben.length)} orang (${pctf(ben.length ? ben.filter(b => b.jk === 'P').length / ben.length * 100 : null)} perempuan).`] });
  sec.push({ h: 'Capaian indikator', table: { head: [o.tpl === 'donor' ? 'Kode donor' : 'Kode', 'Indikator', 'Target', 'Capaian', '%', 'Status'], rows: indRows } });
  if (!ls) sec.push({ h: 'Capaian per landscape', table: { head: ['Landscape', 'Provinsi', 'Rata-rata % capaian', 'Skor kualitas data'], rows: rows('Landscapes').map(l => [l.nama, l.provinsi, pctf(landscapePct(l.id, per)), nf(dqi(l.id).score)]) } });
  sec.push({ h: 'Penerima manfaat terpilah', table: { head: ['Kelompok', 'Perempuan', 'Laki-laki', 'Rentan'], rows: Object.entries(groupBy(ben, b => b.kelompok)).map(([k, v]) => [k, v.filter(b => b.jk === 'P').length, v.filter(b => b.jk === 'L').length, v.filter(b => b.rentan).length]) } });
  if (red.length) sec.push({ h: 'Isu dan tindak lanjut', p: red.map(i => `${i.kode} ${i.nama}: capaian ${pctf(achv(i, ls, per).pct)} dari target. Perlu dibahas di refleksi triwulan.`).concat(rows('Actions').filter(a => a.status !== 'Selesai').map(a => `Tindak lanjut: ${a.tindakan} (PIC ${a.pic}, tenggat ${fdate(a.deadline)}).`)) });
  const st = rows('Stories').filter(s => !ls || s.landscapeId === ls); if (st.length) sec.push({ h: 'Cerita perubahan', p: st.map(s => `${s.judul}. “${s.kutipan}” (${s.narasumber}).`) });
  sec.push({ h: 'Pembelajaran', p: rows('Lessons').filter(l => !ls || l.landscapeId === ls).map(l => `${l.judul}: ${l.rekomendasi}`) });
  return { title, subtitle: `${S.db.Settings.find(s => s.id === 'orgName')?.nilai || 'Blue Forests'} · Periode ${per} · ${lsName}`, date: CONFIG.TODAY, sections: sec };
}
const reportHTML = m => `<article class="report" id="reportDoc"><p class="cover-meta small">${esc(m.subtitle)} · dibuat ${fdate(m.date)}</p><h1>${esc(m.title)}</h1>${m.sections.map(s => `<h2>${esc(s.h)}</h2>${(s.p || []).map(p => `<p>${esc(p)}</p>`).join('')}${s.table ? `<table><thead><tr>${s.table.head.map(h => `<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${s.table.rows.map(r => `<tr>${r.map(c => `<td>${esc(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>` : ''}`).join('')}<p class="small muted" style="margin-top:30px">Dihasilkan otomatis oleh MIS Blue Forests. Angka mengikuti data Approved pada saat laporan dibuat.</p></article>`;
VIEWS.laporan = () => {
  const r = S.f.rep || (S.f.rep = { tpl: 'donor', donor: donors()[0], per: defaultPeriod(), ls: '' });
  const model = buildReport(r); S.lastReport = model;
  const html = pageHead(t('laporan'), 'Laporan dibuat dari data yang sudah disetujui. Pilih template, lalu cetak ke PDF atau buat Google Doc.', `<button class="btn" data-act="printRep">${ic('print')} Cetak / simpan PDF</button><button class="btn primary edit-only" data-act="gdoc">${ic('file')} Buat Google Doc + PDF</button>`) + `
  <div class="grid g-8-4"><div>${reportHTML(model)}</div>
  <div class="no-print"><div class="panel mb"><div class="panel-h"><h2>Pengaturan laporan</h2></div><div class="form" style="grid-template-columns:1fr">
    <div class="f"><label>Template</label><select id="rTpl">${[['donor', 'Laporan donor (crosswalk)'], ['ls', 'Laporan capaian landscape'], ['exec', 'Ringkasan eksekutif']].map(([k, l]) => `<option value="${k}" ${r.tpl === k ? 'selected' : ''}>${l}</option>`).join('')}</select></div>
    ${r.tpl === 'donor' ? `<div class="f"><label>Donor / kerangka</label><select id="rDon">${donors().map(d => `<option ${r.donor === d ? 'selected' : ''}>${esc(d)}</option>`).join('')}</select><span class="hint">Hanya indikator yang dipetakan ke donor ini yang tampil, dengan kode indikator donor.</span></div>` : ''}
    <div class="f"><label>Periode</label><select id="rPer">${periodsSorted().map(p => `<option ${p === r.per ? 'selected' : ''}>${p}</option>`).join('')}</select></div>
    <div class="f"><label>Landscape</label><select id="rLs"><option value="">Semua landscape</option>${rows('Landscapes').map(l => `<option value="${l.id}" ${r.ls === l.id ? 'selected' : ''}>${esc(l.nama)}</option>`).join('')}</select></div></div></div>
  <div class="panel"><div class="panel-h"><h2>Ekspor data per modul</h2><p>CSV dengan BOM agar langsung terbaca di Excel. Data pribadi disamarkan jika penyamaran aktif.</p></div><div class="flex">${['Programs', 'Indicators', 'IndicatorActuals', 'Activities', 'Beneficiaries', 'Stakeholders', 'Evidence', 'Knowledge', 'Documents'].map(tb => `<button class="btn sm" data-act="exportcsv" data-id="${tb}">${ic('down')} ${SCHEMA[tb].label}</button>`).join('')}</div></div></div></div>`;
  return { html, after: () => { const u = (id, k) => { const e = $(id); if (e) e.onchange = ev => { r[k] = ev.target.value; render(); }; }; u('#rTpl', 'tpl'); u('#rDon', 'donor'); u('#rPer', 'per'); u('#rLs', 'ls'); } };
};
ACT.printRep = () => window.print();
ACT.gdoc = async el => {
  if (API.mode !== 'gas') return modal({ title: 'Google Doc + PDF', body: '<p style="margin-top:0">Di versi Apps Script, tombol ini membuat Google Doc dari template di Drive lalu mengekspor PDF-nya. Di versi web lokal, gunakan <b>Cetak / simpan PDF</b>.</p>', foot: '<button class="btn" data-close>Mengerti</button>' });
  el.disabled = true; el.textContent = 'Membuat dokumen…';
  try { const r = await API.generateReport(S.lastReport); modal({ title: 'Laporan siap', body: `<p style="margin-top:0">Dokumen tersimpan di folder Laporan pada Drive.</p><div class="flex"><a class="btn primary" href="${esc(r.docUrl)}" target="_blank" rel="noopener">Buka Google Doc</a><a class="btn" href="${esc(r.pdfUrl)}" target="_blank" rel="noopener">Buka PDF</a></div>` }); }
  catch (e) { toast('Gagal membuat laporan: ' + e.message, 1); } finally { render(); }
};

/* ================= MIGRASI & KUALITAS DATA ================= */
function parseCSV(text) {
  const out = []; let row = [], cell = '', q = false; text = text.replace(/^\ufeff/, '');
  const sep = (text.split('\n')[0].match(/;/g) || []).length > (text.split('\n')[0].match(/,/g) || []).length ? ';' : ',';
  for (let i = 0; i < text.length; i++) { const c = text[i];
    if (q) { if (c === '"' && text[i + 1] === '"') { cell += '"'; i++; } else if (c === '"') q = false; else cell += c; }
    else if (c === '"') q = true; else if (c === sep) { row.push(cell); cell = ''; } else if (c === '\n' || c === '\r') { if (c === '\r' && text[i + 1] === '\n') i++; row.push(cell); if (row.some(x => x !== '')) out.push(row); row = []; cell = ''; } else cell += c; }
  row.push(cell); if (row.some(x => x !== '')) out.push(row); return out;
}
function validateImport(tb, grid) {
  const sc = SCHEMA[tb]; const head = grid[0].map(h => h.trim()); const map = head.map(h => { const f = sc.fields.find(f => norm(f.k) === norm(h) || norm(f.label) === norm(h)); return f ? f.k : (norm(h) === 'id' ? 'id' : null); });
  const missing = sc.fields.filter(f => f.req && !map.includes(f.k)).map(f => f.label); const seen = new Set();
  const res = grid.slice(1).map((r, n) => { const o = {}; map.forEach((k, j) => { if (k) o[k] = (r[j] || '').trim(); }); const err = [], warn = [];
    sc.fields.forEach(f => { let v = o[f.k]; if (v === undefined) return;
      if (f.req && v === '') err.push(`${f.label} kosong`);
      else if (v !== '' && f.type === 'number') { const x = Number(String(v).replace(/\./g, '').replace(',', '.')); if (isNaN(Number(v)) && isNaN(x)) err.push(`${f.label} bukan angka`); else o[f.k] = isNaN(Number(v)) ? x : Number(v); }
      else if (v !== '' && f.type === 'date') { const m = v.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/); if (m) o[f.k] = `${m[3]}-${m[2].padStart(2, '0')}-${m[1].padStart(2, '0')}`; else if (!/^\d{4}-\d{2}-\d{2}$/.test(v)) err.push(`${f.label} bukan tanggal (YYYY-MM-DD)`); }
      else if (v !== '' && f.type === 'bool') o[f.k] = /^(ya|y|true|1|yes)$/i.test(v);
      else if (v !== '' && f.type === 'select') { const op = optionsFor(f); const hit = op.find(x => norm(x) === norm(v)); if (hit) o[f.k] = hit; else err.push(`${f.label} "${v}" tidak ada di master data`); }
      else if (v !== '' && f.type === 'ref') { if (!byId(f.ref, v) && !(f.val && rows(f.ref).some(x => x[f.val] === v))) err.push(`${f.label} "${v}" tidak dikenal`); }
      else if (f.type === 'multi') o[f.k] = v ? v.split(/[;,]/).map(s => s.trim()) : []; });
    if (tb === 'Beneficiaries' && o.nama) { const k = dupKey(o); if (seen.has(k)) err.push('Duplikat di dalam file'); else if (rows('Beneficiaries').some(b => dupKey(b) === k)) warn.push('Mungkin sudah terdaftar'); seen.add(k); if (o.consent === false || o.consent === '') warn.push('Tanpa consent'); }
    if (o.id && byId(tb, o.id)) err.push(`ID ${o.id} sudah ada`);
    return { n: n + 2, o, err, warn }; });
  return { head, map, missing, res };
}
VIEWS.migrasi = () => {
  const tab = curTab('migrasi', 'imp'); let body = '';
  if (tab === 'imp') {
    const V = S.imp; const tb = S.f.impT || 'Beneficiaries';
    body = `<div class="grid g-7-5"><div class="panel"><div class="panel-h"><h2>1. Pilih tabel dan file</h2><p>CSV dari Excel/Google Sheets. Pemisah koma atau titik koma dikenali otomatis.</p></div>
      <div class="filters"><label>Tabel tujuan<select id="impT">${Object.keys(SCHEMA).filter(k => !['AuditLog', 'BackupLog', 'Comments'].includes(k)).map(k => `<option value="${k}" ${tb === k ? 'selected' : ''}>${SCHEMA[k].label} (${k})</option>`).join('')}</select></label><label>File CSV<input type="file" id="impF" accept=".csv,text/csv"></label><button class="btn sm" style="margin-top:16px" data-act="tplCsv" data-id="${tb}">${ic('down')} Unduh template</button></div>
      <details><summary class="small muted" style="cursor:pointer">Atau tempel isi CSV</summary><textarea id="impTxt" placeholder="nama,jk,tglLahir,desa,landscapeId,kelompok…" style="margin-top:8px"></textarea><button class="btn sm mt" id="impPaste">Validasi teks</button></details></div>
      <div class="panel sand"><div class="panel-h"><h2>Aturan validasi</h2></div><p class="small" style="margin:0">Kolom wajib: ${SCHEMA[tb].fields.filter(f => f.req).map(f => `<b>${esc(f.k)}</b>`).join(', ')}.<br>Tanggal YYYY-MM-DD atau DD/MM/YYYY. Nilai pilihan harus ada di master data. Relasi (mis. landscapeId) harus ID yang sudah ada. ${tb === 'Beneficiaries' ? 'Duplikat nama + desa + tanggal lahir ditolak di dalam file, dan diberi peringatan jika sudah ada di sistem.' : ''}</p></div></div>
      ${V ? `<div class="panel mt"><div class="panel-h"><h2>2. Laporan validasi</h2><div class="right"><button class="btn sm" data-act="valRep">${ic('down')} Unduh laporan</button><button class="btn sm primary edit-only" data-act="doImp" ${V.res.filter(r => !r.err.length).length && !V.missing.length ? '' : 'disabled'}>Impor ${V.res.filter(r => !r.err.length).length} baris valid</button></div></div>
        ${V.missing.length ? `<div class="alert err">Kolom wajib tidak ditemukan: ${esc(V.missing.join(', '))}. Periksa baris judul CSV.</div>` : ''}
        <div class="flex mb"><span class="badge green">${V.res.filter(r => !r.err.length && !r.warn.length).length} valid</span><span class="badge yellow">${V.res.filter(r => !r.err.length && r.warn.length).length} valid dengan peringatan</span><span class="badge red">${V.res.filter(r => r.err.length).length} ditolak</span><span class="muted small">Kolom dikenali: ${V.map.filter(Boolean).length}/${V.head.length}${V.map.some(m => !m) ? ' (diabaikan: ' + esc(V.head.filter((h, i) => !V.map[i]).join(', ')) + ')' : ''}</span></div>
        ${table('val', { search: false, pageSize: 10, data: V.res.map(r => ({ ...r, id: r.n })), cols: [{ k: 'n', label: 'Baris', num: 1 }, { k: 's', label: 'Hasil', render: r => r.err.length ? '<span class="badge red">Ditolak</span>' : r.warn.length ? '<span class="badge yellow">Peringatan</span>' : '<span class="badge green">Valid</span>' }, { k: 'd', label: 'Data', render: r => `<span class="small">${esc(Object.values(r.o).slice(0, 4).join(' · '))}</span>` }, { k: 'm', label: 'Catatan', render: r => `<span class="small">${esc(r.err.concat(r.warn).join('; ') || '–')}</span>` }] })}</div>` : ''}`;
  } else {
    const ls = rows('Landscapes'); const q = ls.map(l => ({ l, q: dqi(l.id) }));
    body = `<div class="alert info">Skor kualitas data dihitung otomatis: kelengkapan data penerima (NIK, tanggal lahir, HP, consent), bebas duplikat, ketepatan waktu input terhadap batas lapor, dan persentase capaian yang punya evidence.</div>
    <div class="grid g-7-5"><div class="panel"><div class="chart-box lg"><canvas id="cDq"></canvas></div></div><div>${table('dq', { search: false, data: q.map(x => ({ id: x.l.id, n: x.l.nama, ...x.q })), cols: [{ k: 'n', label: 'Landscape' }, { k: 'complete', label: 'Lengkap', num: 1, render: r => nf(r.complete) }, { k: 'dup', label: 'Unik', num: 1, render: r => nf(r.dup) }, { k: 'timely', label: 'Tepat waktu', num: 1, render: r => nf(r.timely) }, { k: 'ev', label: 'Evidence', num: 1, render: r => nf(r.ev) }, { k: 'score', label: 'Skor', num: 1, render: r => `<b>${nf(r.score)}</b>` }] })}</div></div>`;
    return { html: pageHead(t('migrasi'), 'Impor data lama dengan validasi otomatis, dan pantau kualitas data per landscape.') + tabs('migrasi', [['imp', 'Impor & validasi'], ['dq', 'Skor kualitas data']]) + body,
      after: () => chart('cDq', { type: 'radar', data: { labels: ['Kelengkapan', 'Bebas duplikat', 'Tepat waktu', 'Evidence'], datasets: q.map((x, i) => ({ label: x.l.nama, data: [x.q.complete, x.q.dup, x.q.timely, x.q.ev], borderColor: SERIES[i], backgroundColor: 'transparent', pointRadius: 2 })) }, options: { scales: { r: { min: 0, max: 100, ticks: { display: false } } } } }) };
  }
  return { html: pageHead(t('migrasi'), 'Impor data lama dengan validasi otomatis, dan pantau kualitas data per landscape.') + tabs('migrasi', [['imp', 'Impor & validasi'], ['dq', 'Skor kualitas data']]) + body,
    after: () => { const T = $('#impT'); if (!T) return; T.onchange = e => { S.f.impT = e.target.value; S.imp = null; render(); };
      const run = txt => { const g = parseCSV(txt); if (g.length < 2) return toast('File kosong atau hanya berisi judul kolom.', 1); S.imp = { tb: S.f.impT || 'Beneficiaries', ...validateImport(S.f.impT || 'Beneficiaries', g) }; render(); };
      $('#impF').onchange = e => { const f = e.target.files[0]; if (!f) return; const fr = new FileReader(); fr.onload = () => run(fr.result); fr.readAsText(f); };
      $('#impPaste').onclick = () => run($('#impTxt').value); } };
};
ACT.tplCsv = el => { const sc = SCHEMA[el.dataset.id]; const ex = sc.fields.map(f => f.type === 'date' ? CONFIG.TODAY : f.type === 'number' ? '0' : f.type === 'bool' ? 'ya' : f.type === 'ref' ? (rows(f.ref)[0] || {})[f.val || 'id'] || '' : f.type === 'select' ? (optionsFor(f)[0] || '') : ''); download(`template_${el.dataset.id}.csv`, toCSV(sc.fields.map(f => f.k), [ex])); };
ACT.valRep = () => { const V = S.imp; download(`laporan_validasi_${V.tb}_${CONFIG.TODAY}.csv`, toCSV(['baris', 'hasil', 'error', 'peringatan'], V.res.map(r => [r.n, r.err.length ? 'Ditolak' : r.warn.length ? 'Peringatan' : 'Valid', r.err.join('; '), r.warn.join('; ')]))); };
ACT.doImp = async el => { const V = S.imp; const ok = V.res.filter(r => !r.err.length).map(r => r.o); el.disabled = true;
  try { const out = await API.saveMany(V.tb, ok, CONFIG.USER); out.forEach(r => upsertLocal(V.tb, r)); logLocal('Impor', V.tb, out.length + ' baris'); toast(`${out.length} baris diimpor ke ${SCHEMA[V.tb].label}. ${V.res.length - ok.length} baris ditolak tetap di laporan validasi.`); S.imp = null; render(); } catch (e) { toast('Impor gagal: ' + e.message, 1); el.disabled = false; } };

/* ================= ADMIN ================= */
const MODULES = ['Dashboard', 'Program & Landscape', 'KMEL & Target', 'Input capaian', 'Verifikasi capaian', 'Approval capaian', 'Penerima manfaat (PII)', 'Evidence', 'Pelaporan', 'Admin'];
const ACCESS = { 'Admin': ['K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K', 'K'], 'Manajer Program': ['L', 'K', 'K', 'I', 'V', 'S', 'L', 'I', 'K', '–'], 'MEL Officer': ['L', 'L', 'K', 'I', 'V', '–', 'I', 'K', 'K', '–'], 'Staf Landscape': ['L', 'L', 'L', 'I', '–', '–', 'I', 'I', 'L', '–'], 'Viewer/Donor': ['L', 'L', 'L', '–', '–', '–', '–', 'L', 'L', '–'] };
VIEWS.admin = () => {
  const tab = curTab('admin', 'users'); let body = '', after = null;
  const setting = k => (rows('Settings').find(s => s.id === k) || {}).nilai;
  if (tab === 'users') body = `<div class="alert warn">Versi demo berjalan tanpa login. Di produksi, pengguna masuk dengan akun Google organisasi dan menu mengikuti matriks di bawah; pengecekan juga dilakukan di server.</div><div class="flex mb edit-only"><button class="btn primary" data-act="add" data-id="Users" data-def='${esc(JSON.stringify({ aktif: true, landscapeScope: 'Semua' }))}'>${ic('plus')} Tambah pengguna</button></div>` +
    table('users', { data: rows('Users'), cols: [{ k: 'nama', label: 'Nama' }, { k: 'email', label: 'Email' }, { k: 'role', label: 'Role', render: r => `<span class="badge blue">${esc(r.role)}</span>` }, { k: 'landscapeScope', label: 'Cakupan', render: r => r.landscapeScope === 'Semua' ? 'Semua' : esc(nameOf('Landscapes', r.landscapeScope)) }, { k: 'loginTerakhir', label: 'Login terakhir', render: r => fdate(r.loginTerakhir) }, { k: 'aktif', label: 'Status', render: r => r.aktif ? '<span class="badge green">Aktif</span>' : '<span class="badge">Nonaktif</span>' }], actions: r => crudActs('Users', r) }) +
    `<div class="section-t"><h2>Matriks hak akses</h2><span class="muted small">L = lihat, I = input, V = verifikasi, S = setujui, K = kelola penuh</span></div><div class="table-wrap"><table class="t"><thead><tr><th>Modul</th>${Object.keys(ACCESS).map(r => `<th>${r}</th>`).join('')}</tr></thead><tbody>${MODULES.map((m, i) => `<tr><td>${m}</td>${Object.values(ACCESS).map(a => `<td><span class="badge ${({ K: 'dark', S: 'green', V: 'blue', I: 'yellow', L: '' })[a[i]] || ''}">${a[i]}</span></td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
  else if (tab === 'master') { const kat = S.f.lkK || ''; body = `<div class="filters"><label>Kategori<select data-fk="lkK"><option value="">Semua</option>${uniq(rows('Lookups').map(l => l.kategori)).map(k => `<option ${kat === k ? 'selected' : ''}>${esc(k)}</option>`).join('')}</select></label><button class="btn primary edit-only" style="margin-top:16px" data-act="add" data-id="Lookups" data-def='${esc(JSON.stringify({ kategori: kat, aktif: true }))}'>${ic('plus')} Tambah nilai</button></div>` + table('lk', { data: rows('Lookups').filter(l => !kat || l.kategori === kat), cols: [{ k: 'kategori', label: 'Kategori' }, { k: 'nilai', label: 'Nilai' }, { k: 'aktif', label: 'Aktif', render: r => r.aktif !== false ? '<span class="badge green">Ya</span>' : '<span class="badge">Tidak</span>' }], actions: r => crudActs('Lookups', r) }); after = bindFk; }
  else if (tab === 'dict') body = `<div class="flex mb"><button class="btn" data-act="dictCsv">${ic('down')} Unduh data dictionary</button></div>` + table('dict', { pageSize: 25, data: Object.entries(SCHEMA).flatMap(([tb, s]) => s.fields.map(f => ({ id: tb + '.' + f.k, tb, k: f.k, label: f.label, type: f.type, req: f.req, rel: f.ref || '', pii: f.pii || (s.pii || []).includes(f.k) }))), cols: [{ k: 'tb', label: 'Tabel (sheet)' }, { k: 'k', label: 'Kolom' }, { k: 'label', label: 'Label' }, { k: 'type', label: 'Tipe' }, { k: 'req', label: 'Wajib', render: r => r.req ? 'Ya' : '' }, { k: 'rel', label: 'Relasi ke' }, { k: 'pii', label: 'Data pribadi', render: r => r.pii ? '<span class="badge red">PII</span>' : '' }] });
  else if (tab === 'period') body = table('per', { search: false, data: rows('Periods').sort((a, b) => a.nama.localeCompare(b.nama)), cols: [{ k: 'nama', label: 'Periode' }, { k: 'mulai', label: 'Mulai', render: r => fdate(r.mulai) }, { k: 'selesai', label: 'Selesai', render: r => fdate(r.selesai) }, { k: 'batasLapor', label: 'Batas lapor', render: r => fdate(r.batasLapor) }, { k: 'locked', label: 'Status', render: r => r.locked ? '<span class="badge red">Terkunci</span>' : '<span class="badge green">Terbuka</span>' }], actions: r => `<span class="edit-only flex" style="gap:4px">${act('lockPer', r.id, r.locked ? 'Buka kunci' : 'Kunci', r.locked ? 'unlock' : 'lock')}${iconAct('edit', 'Periods|' + r.id, 'Ubah', 'edit')}</span>` }) + `<div class="flex mt edit-only"><button class="btn" data-act="add" data-id="Periods" data-def='${esc(JSON.stringify({ locked: false }))}'>${ic('plus')} Tambah periode</button></div>`;
  else if (tab === 'audit') { const u = S.f.auU || ''; body = `<div class="filters"><label>Pengguna<select data-fk="auU"><option value="">Semua</option>${uniq(rows('AuditLog').map(a => a.user)).map(x => `<option ${u === x ? 'selected' : ''}>${esc(x)}</option>`).join('')}</select></label><button class="btn" style="margin-top:16px" data-act="exportcsv" data-id="AuditLog">${ic('down')} ${t('export')}</button></div>` + table('audit', { pageSize: 20, data: rows('AuditLog').filter(a => !u || a.user === u), cols: [{ k: 'waktu', label: 'Waktu' }, { k: 'user', label: 'Pengguna' }, { k: 'aksi', label: 'Aksi', render: r => `<span class="badge ${/Hapus/.test(r.aksi) ? 'red' : /Approve|Setuj/.test(r.aksi) ? 'green' : ''}">${esc(r.aksi)}</span>` }, { k: 'tabel', label: 'Tabel' }, { k: 'recordId', label: 'ID data' }, { k: 'detail', label: 'Detail' }] }); after = bindFk; }
  else if (tab === 'backup') body = `<div class="grid g3 mb"><div class="panel kpi"><b>Setiap hari 02.00</b><span>Backup otomatis (time-driven trigger)</span></div><div class="panel kpi"><b>${esc(setting('backupRetensi'))} hari</b><span>Masa simpan backup</span></div><div class="panel kpi"><b>${rows('BackupLog').filter(b => b.status === 'Gagal').length}</b><span>Backup gagal (7 hari)</span></div></div><div class="flex mb edit-only"><button class="btn primary" data-act="bkNow">${ic('refresh')} Backup sekarang</button></div>` +
    table('bk', { search: false, data: rows('BackupLog'), cols: [{ k: 'waktu', label: 'Waktu' }, { k: 'file', label: 'File' }, { k: 'tipe', label: 'Tipe' }, { k: 'ukuran', label: 'Ukuran' }, { k: 'status', label: 'Status', render: r => `<span class="badge ${r.status === 'Berhasil' ? 'green' : 'red'}">${esc(r.status)}</span>` }], actions: r => r.status === 'Berhasil' ? `<span class="edit-only">${act('bkRestore', r.id, 'Pulihkan', '')}</span>` : '' });
  else if (tab === 'trash') { const d = Object.keys(SCHEMA).flatMap(tb => (S.db[tb] || []).filter(r => r._deleted).map(r => ({ id: tb + '|' + r.id, tb, rid: r.id, label: r.nama || r.judul || r.pernyataan || r.tindakan || r.id, at: r._deletedAt || '' })));
    body = `<div class="alert info">Data yang dihapus disimpan di sini selama masa retensi. Pulihkan jika terhapus tidak sengaja.</div>` + table('trash', { data: d, empty: 'Tempat sampah kosong.', cols: [{ k: 'tb', label: 'Tabel', render: r => esc(SCHEMA[r.tb].label) }, { k: 'rid', label: 'ID' }, { k: 'label', label: 'Data' }, { k: 'at', label: 'Dihapus' }], actions: r => `<span class="edit-only flex" style="gap:4px">${act('restore', r.id, 'Pulihkan', 'refresh')}${act('purge', r.id, 'Hapus permanen', 'trash', 'danger')}</span>` }); }
  else if (tab === 'notif') body = `<div class="grid g2"><div class="panel"><div class="panel-h"><h2>Pengingat email</h2></div><div class="form" style="grid-template-columns:1fr">
    <label class="check"><input type="checkbox" id="nOn" ${setting('emailReminder') ? 'checked' : ''}> Kirim pengingat mingguan</label>
    <div class="f"><label>Hari pengiriman</label><select id="nDay">${['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'].map(d => `<option ${setting('reminderHari') === d ? 'selected' : ''}>${d}</option>`).join('')}</select></div>
    <p class="small muted" style="margin:0">Isi pengingat: capaian menunggu verifikasi (ke MEL), menunggu approval (ke manajer), batas pelaporan 14 hari lagi (ke staf landscape), tindak lanjut lewat tenggat (ke PIC).</p></div>
    <div class="flex mt edit-only"><button class="btn primary" data-act="saveNotif">Simpan pengaturan</button><button class="btn" data-act="sendRem">Kirim pengingat sekarang</button></div></div>
    <div class="panel"><div class="panel-h"><h2>Pratinjau notifikasi saat ini</h2></div>${notifications().map(n => `<div class="kitem">${esc(n.t)}<div class="meta">${esc(n.s)}</div></div>`).join('') || '<div class="empty">Tidak ada.</div>'}</div></div>`;
  else if (tab === 'api') { const url = (S.meta.webAppUrl || 'https://script.google.com/macros/s/…/exec'); const tok = setting('apiToken');
    body = `<div class="grid g2"><div class="panel"><div class="panel-h"><h2>API baca (JSON)</h2><p>Untuk website, Metabase, Power BI, atau sistem donor. Hanya data non-pribadi.</p></div>
    <div class="code">GET ${esc(url)}?api=indicators&amp;token=${esc(tok)}
GET ${esc(url)}?api=achievements&amp;periode=2026-Q2&amp;token=…
GET ${esc(url)}?api=landscapes&amp;token=…
GET ${esc(url)}?api=sites&amp;token=…
GET ${esc(url)}?api=activities&amp;landscape=LS-01&amp;token=…</div>
    <p class="small muted">Respons berbentuk <code>{ ok, data, generatedAt }</code>. Token diganti di Script Properties. Data penerima manfaat tidak diekspos lewat API.</p></div>
    <div class="panel"><div class="panel-h"><h2>KoboToolbox</h2><p>Menarik submission formulir lapangan tiap jam ke tabel Aktivitas.</p></div><div class="form" style="grid-template-columns:1fr"><div class="f"><label>Server</label><input type="text" id="kSrv" value="${esc(setting('koboServer'))}"></div><div class="f"><label>Asset ID formulir</label><input type="text" id="kAs" value="${esc(setting('koboAssetId'))}" placeholder="aBcD123…"></div><div class="f"><label>API token</label><input type="password" id="kTk" value="${esc(setting('koboToken'))}" placeholder="disimpan di Script Properties"></div></div><div class="flex mt edit-only"><button class="btn primary" data-act="saveKobo">Simpan</button><button class="btn" data-act="kobo">${ic('refresh')} Sinkron sekarang</button></div></div></div>`; }
  else if (tab === 'usage') { const u = rows('Usage'); const aud = groupBy(rows('AuditLog'), a => a.tabel);
    body = `<div class="grid g4 mb"><div class="panel kpi"><b>${nf(sum(u, x => x.login))}</b><span>Login 30 hari</span></div><div class="panel kpi"><b>${nf(sum(u, x => x.input))}</b><span>Input data 30 hari</span></div><div class="panel kpi"><b>${rows('Users').filter(x => x.aktif).length}</b><span>Pengguna aktif</span></div><div class="panel kpi"><b>${rows('Users').filter(x => x.aktif && x.loginTerakhir < new Date(Date.now() - 14 * 864e5).toISOString().slice(0, 10)).length}</b><span>Tidak login &gt; 14 hari</span></div></div>
    <div class="grid g-7-5"><div class="panel"><div class="panel-h"><h2>Aktivitas harian</h2></div><div class="chart-box"><canvas id="cUse"></canvas></div></div><div class="panel"><div class="panel-h"><h2>Modul paling sering diubah</h2><p>Dari audit trail</p></div><div class="chart-box"><canvas id="cMod"></canvas></div></div></div>`;
    after = () => { chart('cUse', { type: 'line', data: { labels: u.map(x => x.tanggal.slice(5)), datasets: [{ label: 'Login', data: u.map(x => x.login), borderColor: PAL.abyss, tension: .3, pointRadius: 0 }, { label: 'Input data', data: u.map(x => x.input), borderColor: PAL.lagoon, backgroundColor: 'rgba(18,122,134,.1)', fill: true, tension: .3, pointRadius: 0 }] } });
      const k = Object.keys(aud).sort((a, b) => aud[b].length - aud[a].length).slice(0, 6); chart('cMod', { type: 'bar', data: { labels: k, datasets: [{ data: k.map(x => aud[x].length), backgroundColor: PAL.shoal, borderRadius: 4 }] }, options: { indexAxis: 'y', plugins: { legend: { display: false } } } }); }; }
  else body = `<div class="panel">${rows('Changelog').map(c => `<div style="padding:12px 0;border-bottom:1px solid var(--line-2)"><span class="badge dark">v${esc(c.versi)}</span> <span class="muted small">${fdate(c.tanggal)}</span><p style="margin:6px 0 0">${esc(c.catatan)}</p></div>`).join('')}<div class="flex mt edit-only"><button class="btn danger" data-act="reset">Kembalikan data demo ke awal</button></div></div>`;
  return { html: pageHead(t('admin'), 'Pengguna dan hak akses, master data, periode, audit trail, backup, integrasi, dan pemakaian sistem.') + tabs('admin', [['users', 'Pengguna & role'], ['master', 'Master data'], ['dict', 'Data dictionary'], ['period', 'Periode'], ['audit', 'Audit trail'], ['backup', 'Backup'], ['trash', 'Tempat sampah'], ['notif', 'Notifikasi'], ['api', 'Integrasi & API'], ['usage', 'Pemakaian'], ['log', 'Changelog']]) + body, after };
};
const setSetting = (id, nilai) => saveRec('Settings', { ...(rows('Settings').find(s => s.id === id) || { id }), nilai }, 'Pengaturan ' + id);
ACT.dictCsv = () => download(`data_dictionary_${CONFIG.TODAY}.csv`, toCSV(['tabel', 'kolom', 'label', 'tipe', 'wajib', 'relasi', 'pii'], Object.entries(SCHEMA).flatMap(([tb, s]) => s.fields.map(f => [tb, f.k, f.label, f.type, f.req ? 'ya' : '', f.ref || '', f.pii ? 'ya' : '']))));
ACT.bkNow = async el => { el.disabled = true; try { const r = await API.backupNow(CONFIG.USER); upsertLocal('BackupLog', r); toast('Backup selesai: ' + r.file); } catch (e) { toast('Backup gagal: ' + e.message, 1); } render(); };
ACT.bkRestore = async el => { const b = byId('BackupLog', el.dataset.id); if (!(await confirmBox('Pulihkan dari backup', `Semua data akan dikembalikan ke kondisi <b>${esc(b.waktu)}</b>. Backup otomatis dari kondisi sekarang dibuat dulu sebelum pemulihan.`, 'Pulihkan', true))) return;
  try { await API.restoreBackup(b.id, CONFIG.USER); toast(API.mode === 'gas' ? 'Data dipulihkan. Memuat ulang…' : 'Simulasi pemulihan tercatat di audit trail.'); if (API.mode === 'gas') setTimeout(() => location.reload(), 900); } catch (e) { toast('Pemulihan gagal: ' + e.message, 1); } };
ACT.restore = async el => { const [tb, id] = el.dataset.id.split('|'); const r = await API.restore(tb, id, CONFIG.USER); upsertLocal(tb, r); toast('Data dipulihkan.'); render(); };
ACT.purge = async el => { const [tb, id] = el.dataset.id.split('|'); if (!(await confirmBox('Hapus permanen', `Data ${esc(id)} dihapus selamanya dan tidak bisa dipulihkan.`, 'Hapus permanen', true))) return; await API.purge(tb, id, CONFIG.USER, 'Dari tempat sampah'); S.db[tb] = S.db[tb].filter(r => r.id !== id); toast('Dihapus permanen.'); render(); };
ACT.saveNotif = async () => { await setSetting('emailReminder', $('#nOn').checked); await setSetting('reminderHari', $('#nDay').value); toast('Pengaturan notifikasi tersimpan.'); };
ACT.sendRem = async () => { const r = await API.sendReminders(CONFIG.USER); toast(`${r.sent} email pengingat ${r.mode === 'simulasi' ? 'disimulasikan' : 'terkirim'}.`); };
ACT.saveKobo = async () => { await setSetting('koboServer', $('#kSrv').value); await setSetting('koboAssetId', $('#kAs').value); await setSetting('koboToken', $('#kTk').value); toast('Pengaturan KoboToolbox tersimpan.'); };
ACT.reset = async () => { if (!(await confirmBox('Reset data demo', 'Semua perubahan yang dibuat selama demo akan hilang.', 'Reset', true))) return; await API.resetDemo(); location.reload(); };

/* ================= BANTUAN & UMPAN BALIK ================= */
const GUIDE = [['dashboard', 'Lihat capaian ringkas. Ubah filter program, landscape, dan periode. Klik indikator untuk detail.'], ['peta', 'Nyalakan atau matikan layer di kanan atas peta. Pilih landscape untuk melihat capaian indikatornya.'], ['program', 'Kelola struktur Program, Project, Landscape, dan Site. Gunakan tab tabel untuk tambah dan ubah data.'], ['kmel', 'Logframe dan definisi indikator. Revisi target selalu membuat versi baru.'], ['capaian', 'Input nilai per periode, lampirkan evidence, lalu kirim. MEL memverifikasi, manajer menyetujui.'], ['aktivitas', 'Catat kegiatan atau tarik dari KoboToolbox. Verifikasi sebelum dipakai di laporan.'], ['penerima', 'Daftarkan penerima dengan consent. Cek duplikat secara berkala.'], ['evidence', 'Unggah foto, daftar hadir, atau laporan. Tautkan ke indikator dan kegiatan.'], ['laporan', 'Pilih template dan periode, lalu cetak atau buat Google Doc.'], ['migrasi', 'Unduh template, isi di Excel, impor, lalu baca laporan validasinya.']];
VIEWS.bantuan = () => {
  const tab = curTab('bantuan', 'guide'); let body = '';
  if (tab === 'guide') body = `<div class="grid g-7-5"><div><div class="section-t" style="margin-top:0"><h2>Panduan per halaman</h2></div><div class="panel">${GUIDE.map(([k, g]) => `<div style="padding:10px 0;border-bottom:1px solid var(--line-2)"><a href="#${k}"><b>${t(k)}</b></a><p class="small muted" style="margin:3px 0 0">${g}</p></div>`).join('')}</div></div>
    <div><div class="panel sand mb"><div class="panel-h"><h2>Baru pertama kali?</h2></div><p class="small" style="margin-top:0">Tur singkat menunjukkan bagian utama aplikasi dalam enam langkah.</p><button class="btn dark" data-act="tour">Mulai tur</button></div>
    <div class="section-t" style="margin-top:0"><h2>Pertanyaan umum</h2></div><div class="faq">${[['Mengapa capaian saya tidak muncul di dashboard?', 'Dashboard hanya menghitung capaian berstatus Approved. Centang "Hitung juga capaian terverifikasi" untuk melihat angka sementara.'], ['Tombol Setujui tidak aktif.', 'Capaian wajib punya minimal satu evidence. Buka ubah capaian, lalu centang evidence yang sesuai.'], ['Saya salah input di periode yang sudah dikunci.', 'Minta Admin membuka kunci periode di menu Admin › Periode. Alasannya tercatat di audit trail.'], ['Bagaimana mengisi data saat tidak ada sinyal?', 'Gunakan formulir KoboCollect offline. Data masuk otomatis saat sinkron dan berstatus Perlu Verifikasi.'], ['Siapa yang bisa melihat NIK dan nomor HP?', 'Hanya Admin, Manajer Program, dan MEL Officer. Role lain melihat data tersamar, dan ekspor CSV ikut tersamar.'], ['Data terhapus tidak sengaja.', 'Buka Admin › Tempat sampah, lalu pulihkan. Untuk kerusakan besar, pulihkan dari backup harian.']].map(([q, a]) => `<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></div></div>`;
  else { const cols = ['Open', 'In Progress', 'Fixed', 'Verified']; const fb = rows('Feedback');
    body = `<div class="grid g4 mb">${['Critical', 'Major', 'Minor'].map(s => `<div class="panel kpi"><b>${fb.filter(f => f.severity === s && f.status !== 'Verified').length}</b><span>${s} belum selesai</span></div>`).join('')}<div class="panel kpi"><b>${fb.filter(f => f.status === 'Verified').length}</b><span>Sudah diverifikasi</span></div></div>
    <p class="muted small">Dipakai sebagai daftar temuan UAT (Deliverable 3) dan log perbaikan masa stabilisasi (Deliverable 6).</p>
    <div class="kanban">${cols.map((c, ci) => `<div class="kcol"><h3>${c} <span class="badge">${fb.filter(f => f.status === c).length}</span></h3>${fb.filter(f => f.status === c).map(f => `<div class="kitem"><span class="badge ${({ Critical: 'red', Major: 'yellow', Minor: '' })[f.severity]}">${esc(f.severity)}</span> <span class="muted small">${esc(f.id)} · ${esc(f.halaman)}</span><p style="margin:6px 0 0">${esc(f.deskripsi)}</p><div class="meta">${esc(f.pelapor)} · ${fdate(f.tanggal)}</div><div class="flex mt edit-only" style="gap:4px">${ci > 0 ? `<button class="btn sm" data-act="mvFb" data-id="${f.id}|${cols[ci - 1]}">‹</button>` : ''}${ci < 3 ? `<button class="btn sm primary" data-act="mvFb" data-id="${f.id}|${cols[ci + 1]}">${cols[ci + 1]} ›</button>` : ''}${iconAct('edit', 'Feedback|' + f.id, 'Ubah', 'edit')}</div></div>`).join('')}</div>`).join('')}</div>`; }
  return pageHead(t('bantuan'), 'Panduan, pertanyaan umum, dan pelacak masalah untuk UAT dan masa stabilisasi.', `<button class="btn primary" data-act="bug">${ic('bug')} ${t('report')}</button>`) + tabs('bantuan', [['guide', 'Panduan & FAQ'], ['bug', `Pelacak masalah (${rows('Feedback').filter(f => f.status !== 'Verified').length})`]]) + body;
};
ACT.mvFb = async el => { const [id, st] = el.dataset.id.split('|'); await saveRec('Feedback', { ...byId('Feedback', id), status: st }, 'Status → ' + st); render(); };
ACT.bug = () => openForm('Feedback', null, { only: ['halaman', 'deskripsi', 'severity', 'infoTeknis'], defaults: { halaman: t(S.view), status: 'Open', pelapor: CONFIG.USER, tanggal: CONFIG.TODAY, severity: 'Minor', infoTeknis: `${navigator.userAgent.split(') ')[0].split('(')[1] || 'browser'} · layar ${innerWidth}×${innerHeight} · mode ${API.mode}` },
  note: '<div class="alert info">Jelaskan apa yang Anda lakukan dan apa yang terjadi. Halaman dan info teknis terisi otomatis.</div>', after: () => { toast('Laporan terkirim ke tim pengembang. Terima kasih.'); render(); } });

/* ---------- tur ---------- */
const TOUR = [['#nav', 'Menu utama dikelompokkan dari ringkasan sampai pengaturan sistem.'], ['#gsearch', 'Cari apa saja: indikator, desa, nama penerima, atau dokumen.'], ['#bell', 'Notifikasi berisi capaian yang menunggu verifikasi, tenggat pelaporan, dan data ganda.'], ['.nav a[data-view=capaian]', 'Alur inti: input capaian, verifikasi MEL, lalu approval manajer dengan evidence.'], ['.fab', 'Temukan kendala? Laporkan dari halaman mana pun.'], ['[data-act=pub]', 'Mode publik menampilkan ringkasan tanpa data pribadi untuk dibagikan.']];
ACT.tour = () => { let i = 0; const tip = document.createElement('div'); tip.className = 'tour-tip'; document.body.appendChild(tip);
  const step = () => { $$('.tour-hl').forEach(e => e.classList.remove('tour-hl')); if (i >= TOUR.length) { tip.remove(); return; } const el = $(TOUR[i][0]); if (!el) { i++; return step(); } el.classList.add('tour-hl'); el.scrollIntoView({ block: 'nearest' }); const r = el.getBoundingClientRect();
    tip.innerHTML = `<b>${i + 1} dari ${TOUR.length}</b><p>${TOUR[i][1]}</p><div class="flex"><button class="btn sm" id="tSkip">Lewati</button><button class="btn sm primary" id="tNext">${i === TOUR.length - 1 ? 'Selesai' : 'Lanjut'}</button></div>`;
    tip.style.top = Math.min(innerHeight - 170, r.bottom + 10) + 'px'; tip.style.left = Math.max(10, Math.min(innerWidth - 320, r.left)) + 'px';
    $('#tNext', tip).onclick = () => { i++; step(); }; $('#tSkip', tip).onclick = () => { i = TOUR.length; step(); }; };
  step(); };

/* ================= BOOT ================= */
async function boot() {
  $('#app').innerHTML = '<div class="loading"><i></i><span>Memuat data MIS…</span></div>';
  try { const d = await API.getAll(); S.meta = d._meta || {}; delete d._meta; S.db = d; Object.keys(SCHEMA).forEach(k => S.db[k] = S.db[k] || []); ['Settings', 'Changelog', 'Usage'].forEach(k => S.db[k] = S.db[k] || []);
    S.view = location.hash.slice(1) || 'dashboard'; remount(); }
  catch (e) { $('#app').innerHTML = `<div class="loading"><b>Data gagal dimuat.</b><span>${esc(e.message)}</span><span class="small">Di Apps Script, jalankan fungsi <code>setupDatabase</code> sekali dari editor, lalu muat ulang halaman.</span></div>`; }
}
document.readyState === 'loading' ? document.addEventListener('DOMContentLoaded', boot) : boot();
